version: '3'

services:
  bouncer:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/bouncer
    env_file:
      - environments/dev
    links:
      - database
    network_mode: bridge

  database:
    image: postgres
    env_file:
      - environments/dev
    volumes:
      - db_data:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  db_data:
